version: "0.2"
phases:
  install:
    runtime-version:
      nodejs: 14
  pre_build:
    commands:
      - echo "installing dependencies"
      - npm install
  build:
    commands:
      - echo "starting compilation"
      - npm run build:prod
  post_build:
    commands:
      - aws s3 rm s3://cursoangular09 --recursive
      - aws s3 sync ./dist/aplicacion s3://cursoangular09 --acl 'public-read' --delete
      - aws cloudfront create-invalidation --distribution-id E2G8YBWD6U2C4V --paths '/*'
artifacts:
  name: "BuildOutput"
  files:
    - "**/*"
  base-directory: "dist/aplicacion"
